import {
  Code2,
  Palette,
  Camera,
  NotebookPen,
  Calculator,
  LineChart,
  Ruler,
  Wrench,
  BookOpen,
  BriefcaseMedical,
  UtensilsCrossed,
  Scissors,
  Hammer,
  Truck,
  Dumbbell,
  Megaphone,
  Gavel,
  Building2,
  ShoppingBag,
  Languages,
  Newspaper,
  Stethoscope,
  Sparkles,
  Pill,
  PawPrint,
  Brain,
  Flower2,
  Zap,
  PaintRoller,
  Shirt,
  Gem,
  Flower,
  Trees,
  Key,
  Croissant,
  Beer,
  Coffee,
  Utensils,
  Music,
  Music4,
  Drama,
  PartyPopper,
  Bug,
  BarChart3,
  LayoutDashboard,
  FlaskConical,
  FlaskRound,
  Car,
  Plane,
  Sailboat,
  Bike,
  Wheat,
  Fish,
  GraduationCap,
  Activity,
  PersonStanding,
  Brush,
  Map,
  Shield,
  Video,
  Film,
  type LucideIcon,
} from "lucide-react";

export type ProfessionAvatar = {
  id: string;
  Icon: LucideIcon;
  bg: string;
  fg: string;
};

/**
 * Mobil uygulamadaki ProfessionAvatars listesiyle aynı 60 öğe — Material Icons
 * yerine Lucide ile eşleştirildi, renk paleti birebir taşındı.
 */
export const PROFESSION_AVATARS: ProfessionAvatar[] = [
  { id: "developer", Icon: Code2, bg: "#E0F2FE", fg: "#0284C7" },
  { id: "designer", Icon: Palette, bg: "#FCE7F3", fg: "#DB2777" },
  { id: "photographer", Icon: Camera, bg: "#E0E7FF", fg: "#4F46E5" },
  { id: "writer", Icon: NotebookPen, bg: "#FEF3C7", fg: "#D97706" },
  { id: "accountant", Icon: Calculator, bg: "#DCFCE7", fg: "#059669" },
  { id: "consultant", Icon: LineChart, bg: "#E0F2FE", fg: "#0369A1" },
  { id: "architect", Icon: Ruler, bg: "#F1F5F9", fg: "#475569" },
  { id: "engineer", Icon: Wrench, bg: "#FFE4E6", fg: "#BE123C" },
  { id: "teacher", Icon: BookOpen, bg: "#EDE9FE", fg: "#7C3AED" },
  { id: "doctor", Icon: BriefcaseMedical, bg: "#FEE2E2", fg: "#DC2626" },
  { id: "chef", Icon: UtensilsCrossed, bg: "#FFEDD5", fg: "#EA580C" },
  { id: "barber", Icon: Scissors, bg: "#F3E8FF", fg: "#9333EA" },
  { id: "mechanic", Icon: Hammer, bg: "#FEF3C7", fg: "#B45309" },
  { id: "driver", Icon: Truck, bg: "#E0F2FE", fg: "#0E7490" },
  { id: "trainer", Icon: Dumbbell, bg: "#DCFCE7", fg: "#15803D" },
  { id: "marketing", Icon: Megaphone, bg: "#FCE7F3", fg: "#BE185D" },
  { id: "lawyer", Icon: Gavel, bg: "#F1F5F9", fg: "#334155" },
  { id: "realEstate", Icon: Building2, bg: "#E0F2FE", fg: "#075985" },
  { id: "salesperson", Icon: ShoppingBag, bg: "#DCFCE7", fg: "#047857" },
  { id: "translator", Icon: Languages, bg: "#E0E7FF", fg: "#3730A3" },
  { id: "journalist", Icon: Newspaper, bg: "#F1F5F9", fg: "#475569" },
  { id: "nurse", Icon: Stethoscope, bg: "#FEE2E2", fg: "#B91C1C" },
  { id: "dentist", Icon: Sparkles, bg: "#E0F2FE", fg: "#0EA5E9" },
  { id: "pharmacist", Icon: Pill, bg: "#DCFCE7", fg: "#15803D" },
  { id: "veterinarian", Icon: PawPrint, bg: "#FFEDD5", fg: "#C2410C" },
  { id: "psychologist", Icon: Brain, bg: "#EDE9FE", fg: "#6D28D9" },
  { id: "masseur", Icon: Flower2, bg: "#FAE8FF", fg: "#A21CAF" },
  { id: "electrician", Icon: Zap, bg: "#FEF3C7", fg: "#B45309" },
  { id: "plumber", Icon: Wrench, bg: "#E0F2FE", fg: "#0891B2" },
  { id: "carpenter", Icon: Hammer, bg: "#FEF3C7", fg: "#92400E" },
  { id: "painter", Icon: PaintRoller, bg: "#FCE7F3", fg: "#BE185D" },
  { id: "tailor", Icon: Shirt, bg: "#E0E7FF", fg: "#4338CA" },
  { id: "jeweler", Icon: Gem, bg: "#E0F2FE", fg: "#0891B2" },
  { id: "florist", Icon: Flower, bg: "#FCE7F3", fg: "#DB2777" },
  { id: "gardener", Icon: Trees, bg: "#DCFCE7", fg: "#15803D" },
  { id: "cleaner", Icon: Sparkles, bg: "#E0F2FE", fg: "#0369A1" },
  { id: "locksmith", Icon: Key, bg: "#F1F5F9", fg: "#525252" },
  { id: "baker", Icon: Croissant, bg: "#FEF3C7", fg: "#B45309" },
  { id: "bartender", Icon: Beer, bg: "#FFE4E6", fg: "#BE123C" },
  { id: "cafeOwner", Icon: Coffee, bg: "#FEF3C7", fg: "#78350F" },
  { id: "catering", Icon: Utensils, bg: "#FFEDD5", fg: "#C2410C" },
  { id: "musician", Icon: Music, bg: "#EDE9FE", fg: "#7C3AED" },
  { id: "dj", Icon: Music4, bg: "#FAE8FF", fg: "#A21CAF" },
  { id: "dancer", Icon: PersonStanding, bg: "#FCE7F3", fg: "#BE185D" },
  { id: "actor", Icon: Drama, bg: "#FEE2E2", fg: "#B91C1C" },
  { id: "eventPlanner", Icon: PartyPopper, bg: "#FCE7F3", fg: "#C026D3" },
  { id: "tester", Icon: Bug, bg: "#DCFCE7", fg: "#047857" },
  { id: "dataAnalyst", Icon: BarChart3, bg: "#E0F2FE", fg: "#0369A1" },
  { id: "productManager", Icon: LayoutDashboard, bg: "#E0E7FF", fg: "#4F46E5" },
  { id: "scientist", Icon: FlaskConical, bg: "#EDE9FE", fg: "#6D28D9" },
  { id: "chemist", Icon: FlaskRound, bg: "#E0F2FE", fg: "#0891B2" },
  { id: "taxi", Icon: Car, bg: "#FEF3C7", fg: "#CA8A04" },
  { id: "pilot", Icon: Plane, bg: "#E0F2FE", fg: "#0284C7" },
  { id: "sailor", Icon: Sailboat, bg: "#E0E7FF", fg: "#1D4ED8" },
  { id: "courier", Icon: Bike, bg: "#FFEDD5", fg: "#EA580C" },
  { id: "farmer", Icon: Wheat, bg: "#DCFCE7", fg: "#166534" },
  { id: "fisherman", Icon: Fish, bg: "#E0F2FE", fg: "#0369A1" },
  { id: "tutor", Icon: GraduationCap, bg: "#EDE9FE", fg: "#6D28D9" },
  { id: "fitnessCoach", Icon: Activity, bg: "#DCFCE7", fg: "#15803D" },
  { id: "yogaInstructor", Icon: PersonStanding, bg: "#FAE8FF", fg: "#9333EA" },
  { id: "makeupArtist", Icon: Sparkles, bg: "#FCE7F3", fg: "#C026D3" },
  { id: "nailArtist", Icon: Brush, bg: "#FAE8FF", fg: "#A21CAF" },
  { id: "tourGuide", Icon: Map, bg: "#E0F2FE", fg: "#0891B2" },
  { id: "securityGuard", Icon: Shield, bg: "#F1F5F9", fg: "#334155" },
  { id: "videographer", Icon: Video, bg: "#E0E7FF", fg: "#4F46E5" },
  { id: "contentCreator", Icon: Film, bg: "#FCE7F3", fg: "#DB2777" },
];
